### ISSUE TITLE
Only relevant commits for range

### ISSUE THREAD

**Issue by cpfaff** [junegunn/gv.vim#13]
Will there be a command to only show relevant commits to a range of lines that have been visual selected?

**Comment by junegunn** [comment]
Interesting suggestion, thanks. `:GV` command is now enabled in visual mode and in that case `-L` option is set which tracks down the commits for the selected lines. Needs some polishing though, but it works as expected.

**Comment by cpfaff** [comment]
Wow that was fast thank you. Tried it and it works nicely. However I find it a bit confusing having the patches listed all in one buffer all opened to browse through. Could you implement the same behaviour as it is with just calling `:GV`. Having a browser like experience and that selecting a commit on the left then opens the patch on the right? That would be amazing.

**Comment by junegunn** [comment]
I felt the same way at first. But that's how `git log -L` works, and this plugin does not perform any post-processing on the output of the command which is why it's much faster than gitv, and I'm not going to change that. So until git adds a native option to exclude the diff content, we'll stick with the current format. Note that you can move between commits with `]]` and `[[` mappings. Those might help in a little.

**Comment by cpfaff** [comment]
OK. Thanks. I will try out the mappings.

**Comment by idbrii** [comment]
> until git adds a native option to exclude the diff content, we'll stick with the current format.

I was interested in seeing what the commit-only view would look like. Git log got a `--no-patch` [around 2019](https://github.com/git/git/commit/2be45868a840f65ae16d171b5ae503846fa17b95). You could add it to GV:

```
diff --git a/plugin/gv.vim b/plugin/gv.vim
index 9de8d4b..237aac0 100644
--- a/plugin/gv.vim
+++ b/plugin/gv.vim
@@ -202,7 +202,7 @@ function! s:log_opts(bang, visual, line1, line2)
   if a:visual || a:bang
     let current = expand('%')
     call s:check_buffer(current)
-    return a:visual ? [[printf('-L%d,%d:%s', a:line1, a:line2, current)], []] : [['--follow'], ['--', current]]
+    return a:visual ? [['--no-patch', printf('-L%d,%d:%s', a:line1, a:line2, current)], []] : [['--follow'], ['--', current]]
   endif
   return [['--graph'], []]
 endfunction
```

However, this change makes it difficult to see how the selected lines changed since the list of commits shows the full patch when selected. (Which is great for general log, but less useful for this more targeted view.) The current implementation shows only the changes to selected lines. Since you can still select a commit to view full patch and navigate with `]]`, it still seems more useful. I wouldn't propose changing anything.
