### ISSUE TITLE
Shortcut for next/prev commit

### ISSUE THREAD

**Issue by firedev** [junegunn/gv.vim#6]
Hi, thank you for GV. I was using Gitv but didn't work that well.

Is there a way to have shortcuts for next/prev commit?

**Comment by junegunn** [comment]
Not sure if I understood your question correctly, but you seem to want shortcuts to `jo` and `ko`, right? Since this plugin sets the filetype of the browser buffer to `"GV"`, you can use `FileType GV` autocmd to set up custom mappings like follows.

```vim
" Version 1
autocmd! filetype GV nmap <buffer> <c-n> jo
autocmd  filetype GV nmap <buffer> <c-p> ko
```

Makes sense? We can slightly improve the mappings to skip lines without commit hash in the list.

```vim
" Version 2
autocmd! filetype GV nmap <buffer> <silent> <c-n> :call search('^.*[a-z0-9]')<cr>o
autocmd  filetype GV nmap <buffer> <silent> <c-p> :call search('^.*[a-z0-9]', 'b')<cr>o
```

The problem with the above mappings is that when GV is first started and the split on the right side is not yet open, `<c-n>` will directly go to the second commit. We can correct this by checking the number of windows on the tab.

```vim
" Version 3
autocmd! filetype GV nmap <buffer> <silent> <c-n> :if winnr('$') > 1<bar>call search('^.*[a-z0-9]')<bar>endif<cr>o
autocmd  filetype GV nmap <buffer> <silent> <c-p> :if winnr('$') > 1<bar>call search('^.*[a-z0-9]', 'b')<bar>endif<cr>o
```

I could probably add these mappings to the code so that they are activated by default, but for now, I'd like to keep things as simple as possible. Does this answer your question?

**Comment by firedev** [comment]
Thank you for your details explanation. Sorry I wasn't too clear about the question. 

Is it possible to go to the next commit while staying in the preview window? So you can browse the history without leaving it. Sort of like you can do with fugitive's `:Glog` for the current file.

**Comment by junegunn** [comment]
Fugitive mappings are available in the buffer. So `P` will bring you to the parent commit, though it won't synchronize the cursor on the browser window. I'll make GV fire a User autocmd so one can setup custom mappings on the buffer.
